### ISSUE TITLE
Trying to use for Bounty Castle towards Haxe and getting error.

### ISSUE THREAD

**Issue by al-sabr** [FizzerWL/Cs2hx#4] opened 2020-06-12 22:11 UTC
**Cs2hx.exe /sln:G:\\programming\\c#\\bccrypto-csharp-1.8.6\\csharp.sln**

```
Exception:
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. 2 errors:
  warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
  error CS5001: Program does not contain a static 'Main' method suitable for an entry point
   at Cs2hx.Program.Build() in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 68
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Cs2hx.Utility.Parallel[T](IEnumerable`1 list, Action`1 action, Boolean parallel) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Utility.cs:line 20
   at Cs2hx.Program.Go(Compilation compilation, String outDir, IEnumerable`1 extraTranslation, String ctorHelperName, HashSet`1 whitelist, Boolean buildFirst) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at Cs2hx.EntryPoint.Main(String[] args) in G:\programming\c#\Cs2hx\trunk\Cs2hx\EntryPoint.cs:line 0
---> (Inner Exception #0) System.Exception: Build failed. 2 errors:
  warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
  error CS5001: Program does not contain a static 'Main' method suitable for an entry point
   at Cs2hx.Program.Build() in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 68
   at Cs2hx.Program.<>c.<Go>b__8_2(Action a) in G:\programming\c#\Cs2hx\trunk\Cs2hx\Program.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

```

**Comment by FizzerWL** [comment] 2020-06-13 00:34
Duplicate of #3

**Closed as completed by FizzerWL** 2020-06-13 00:34 UTC

**Comment by al-sabr** [comment] 2020-06-13 12:16
How do we make the Dll project conversion then ? I have no clue how to do this to work.
Can you provide assistance please?

I am not C# savvy
